version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./Disease_model.h5:/app/Disease_model.h5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:8090
    depends_on:
      - backend