version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:127.0.0.1:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:127.0.0.1:8090