version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./saved_models1:/app/saved_models1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:8090
    depends_on:
      - backend